# Upload a Python Package using Twine when a release is created

name: release
on:  # yamllint disable-line rule:truthy
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
      - run: python -m build --sdist --wheel
      - run: twine check --strict dist/*
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          include-hidden-files: true

  pypi-upload:
    needs: package
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      id-token: write  # for trusted publishing
    environment:
      name: pypi
      url: https://pypi.org/p/pyprep
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'release'
